id: P004444
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:22:18.437486
source_metadata:
  id: bdr:W1KG12370
  title: རྒྱ་བོད་ཀྱི་ཆོས་འབྱུང་རིན་པོ་ཆེ།
  author: ''
  volumes:
    a7741f6cbc834b378179fc3f3b1f4708:
      image_group_id: I1KG12399
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
